Repository soffan-group-25/decide, pull requests merged in 2023-01, with the labels that each got.

#41 doc: Improve README
  README.md
  docs/CONTRIBUTING.md
  docs/README.md
  docs/decide.pdf
Labels: documentation

#42 feat: Add LIC 0
  decide/lic0.cpp
  decide/lic0.test.cpp
Labels: enhancement

#52 feat: Add file for util functions
  decide/utils.hpp
Labels: documentation

#59 feat: Add LIC12
  decide/lic12.cpp
  decide/lic12.test.cpp
  decide/lics.hpp
Labels: enhancement

#58 fix: Include all .cpp and .hpp files in "make format"
  Makefile
Labels: bug

#69 feat: Add LIC11
  decide/lic11.cpp
  decide/lic11.test.cpp
  decide/lics.hpp
Labels: enhancement

#76 fix: Change paths in makefile so that "make test" works properly
  Makefile
Labels: Blocker

#34 feat: add LIC 5
  decide/lic5.cpp
  decide/lic5.test.cpp
  decide/lics.hpp
Labels: enhancement

#83 Make `Coordinate` equality operator const
  decide/decide.hpp
Labels: bug, Blocker

#84 fix: Fix LIC12 OBOE
  decide/lic12.cpp
Labels: bug

#86 fix: Fix LIC0
  decide/lic0.cpp
  decide/lic0.test.cpp
Labels: bug

#60 feat: Add LIC1
  decide/lic1.cpp
  decide/lic1.test.cpp
  decide/lics.hpp
Labels: enhancement

#67 feat: Add function to utils for checking if points can be contained by circle
  decide/utils.hpp
Labels: enhancement, Blocker

#88 feat: Implement PUM functionality
  decide/decide.cpp
  decide/decide.hpp
  decide/decide.test.cpp
Labels: enhancement

#62 feat: Add function that calculates triangle area
  decide/utils.hpp
  decide/utils.test.cpp
Labels: enhancement

#95 feat: Add LIC10
  decide/lic10.cpp
  decide/lic10.test.cpp
  decide/lics.hpp
Labels: enhancement

#96 feat: Add angle between points function
  decide/utils.hpp
  decide/utils.test.cpp
Labels: enhancement

#92 feat: Add FUV
  decide/decide.cpp
  decide/decide.hpp
  decide/decide.test.cpp
Labels: enhancement

#74 feat: Add LIC6
  decide/lic6.cpp
  decide/lic6.test.cpp
  decide/lics.hpp
Labels: enhancement

#78 feat: add LIC 14
  decide/lic14.cpp
  decide/lic14.tests.cpp
Labels: enhancement

#53 feat: Add LIC8
  decide/lic8.cpp
  decide/lic8.test.cpp
  decide/lics.hpp
Labels: enhancement

#61 Feat: Add LIC 4
  decide/lic4.cpp
  decide/lic4.test.cpp
  decide/lics.hpp
Labels: enhancement

#80 feat: Add LIC #9
  decide/lic9.cpp
  decide/lic9.test.cpp
  decide/lics.hpp
Labels: enhancement

#99 feat: Add LIC 2
  decide/lic2.cpp
  decide/lic2.test.cpp
Labels: enhancement

#102 fix: Add missing LIC declarations
  decide/lics.hpp
Labels: bug

#104 fix: Solves util declaration problems
  Makefile
  decide/lic2.cpp
  decide/lic9.cpp
  decide/utils.cpp
  decide/utils.hpp
Labels: bug

#100 feat: ADD LIC #3
  decide/lic3.cpp
  decide/lic3.test.cpp
Labels: enhancement

#94 feat: Add launch
  .gitignore
  Makefile
  decide/decide.cpp
  decide/decide.hpp
  decide/decide.test.cpp
  decide/main.cpp
  tests/launch/decisions.cpp
Labels: enhancement

#106 fix: Renames LIC14 test file
  decide/lic14.test.cpp
Labels: bug

#113 doc: Update contribution rules
  docs/CONTRIBUTING.md
Labels: documentation

#121 fix: Make LIC10 use util function for triangle area
  decide/lic10.cpp
Labels: bug
